//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.SWEHubAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWEHubAPI.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Crime", ReplyAction="http://tempuri.org/IService1/CrimeResponse")]
        string Crime(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Crime", ReplyAction="http://tempuri.org/IService1/CrimeResponse")]
        System.Threading.Tasks.Task<string> CrimeAsync(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Weather", ReplyAction="http://tempuri.org/IService1/WeatherResponse")]
        string Weather(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Weather", ReplyAction="http://tempuri.org/IService1/WeatherResponse")]
        System.Threading.Tasks.Task<string> WeatherAsync(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/test", ReplyAction="http://tempuri.org/IService1/testResponse")]
        int test(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/test", ReplyAction="http://tempuri.org/IService1/testResponse")]
        System.Threading.Tasks.Task<int> testAsync(int num);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleApp.SWEHubAPI.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleApp.SWEHubAPI.IService1>, ConsoleApp.SWEHubAPI.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Crime(string state) {
            return base.Channel.Crime(state);
        }
        
        public System.Threading.Tasks.Task<string> CrimeAsync(string state) {
            return base.Channel.CrimeAsync(state);
        }
        
        public string Weather(string state) {
            return base.Channel.Weather(state);
        }
        
        public System.Threading.Tasks.Task<string> WeatherAsync(string state) {
            return base.Channel.WeatherAsync(state);
        }
        
        public int test(int num) {
            return base.Channel.test(num);
        }
        
        public System.Threading.Tasks.Task<int> testAsync(int num) {
            return base.Channel.testAsync(num);
        }
    }
}
